# Generated by Django 3.0 on 2019-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrodoce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, default=50, max_digits=1000000)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
