# Generated by Django 3.0 on 2019-12-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agrodoce', '0003_auto_20191210_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
    ]
